### ISSUE TITLE
Widget Tests with Wiredash

### ISSUE THREAD

**Issue by passsy** [wiredashio/wiredash-sdk#113]
I'm not able to execute my tests after wrapping my app in Wiredash.

```
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following MissingPluginException was thrown running a test:
MissingPluginException(No implementation found for method getAll on channel
plugins.flutter.io/shared_preferences)

When the exception was thrown, this was the stack:
#2      SharedPreferences.getInstance (package:shared_preferences/shared_preferences.dart:63:20)
#5      PlatformBuildInfo._getDeviceID (package:wiredash/src/common/utils/build_info.dart:52:43)
#6      new PlatformBuildInfo (package:wiredash/src/common/utils/build_info.dart:24:5)
#7      WiredashState.initState (package:wiredash/src/wiredash_widget.dart:160:41)
#8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4765:58)
#9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
...     Normal element mounting (67 frames)
#76     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
#77     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
#78     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
```

Wiredash should not access the shared_preferences until called.

**Comment by passsy** [comment]
# Solution

Add this line to your tests before pumping a `Widget` containing `Wiredash`
```dart
SharedPreferences.setMockInitialValues({});
```
