### ISSUE TITLE
Compatibility with platform views

### ISSUE THREAD

**Issue by passsy** [wiredashio/wiredash-sdk#118]
While showing a Google Map I go this error. Everything works but I'm not sure what exactly causes it.

Keeping it here without reproducible minimal example to look into it later

```
I/flutter (13124): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (13124): The following assertion was thrown during paint():
I/flutter (13124): 'package:flutter/src/rendering/layer.dart': Failed assertion: line 1586 pos 12:
I/flutter (13124): 'value!.storage.every((double component) => component.isFinite)': is not true.
I/flutter (13124): 
I/flutter (13124): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (13124): more information in this error message to help you determine and fix the underlying cause.
I/flutter (13124): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (13124):   https://github.com/flutter/flutter/issues/new?template=BUG.md
I/flutter (13124): 
I/flutter (13124): The relevant error-causing widget was:
I/flutter (13124):   Wiredash file:///Users/pascalwelsch/Project/lib/app.dart:64:12
I/flutter (13124): 
I/flutter (13124): When the exception was thrown, this was the stack:
I/flutter (13124): #2      TransformLayer.transform= (package:flutter/src/rendering/layer.dart:1586:12)
I/flutter (13124): #3      PaintingContext.pushTransform (package:flutter/src/rendering/object.dart:576:13)
I/flutter (13124): #4      RenderTransform.paint (package:flutter/src/rendering/proxy_box.dart:2298:25)
I/flutter (13124): #5      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
I/flutter (13124): #6      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
I/flutter (13124): #7      RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2616:15)
I/flutter (13124): #8      RenderStack.paintStack (package:flutter/src/rendering/stack.dart:606:5)
I/flutter (13124): #9      RenderStack.paint (package:flutter/src/rendering/stack.dart:614:7)
I/flutter (13124): #10     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
I/flutter (13124): #11     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
I/flutter (13124): #12     _RenderColoredBox.paint (package:flutter/src/widgets/basic.dart:7318:15)
I/flutter (13124): #13     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
I/flutter (13124): #14     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
I/flutter (13124): #15     RenderView.paint (package:flutter/src/rendering/view.dart:214:15)
I/flutter (13124): #16     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2311:7)
I/flutter (13124): #17     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:140:11)
I/flutter (13124): #18     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
I/flutter (13124): #19     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:978:29)
I/flutter (13124): #20     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:438:19)
I/flutter (13124): #21     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:914:13)
I/flutter (13124): #22     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:302:5)
I/flutter (13124): #23     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
I/flutter (13124): #24     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
I/flutter (13124): #25     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:864:7)
I/flutter (13124): (elided 6 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, and dart:async-patch)
I/flutter (13124): 
I/flutter (13124): The following RenderObject was being processed when the exception was fired: RenderTransform#9a27e:
I/flutter (13124):   needs compositing
I/flutter (13124):   creator: Transform ← AnimatedBuilder ← Stack ← _InheritedProviderScope<SketcherController> ←
I/flutter (13124):     ChangeNotifierProvider<SketcherController> ← _NestedHook ← _InheritedProviderScope<CaptureUiState>
I/flutter (13124):     ← ValueListenableProvider<CaptureUiState> ← _NestedHook ← MultiProvider ←
I/flutter (13124):     Capture-[LabeledGlobalKey<CaptureState>#aa9c1] ← ColoredBox ← ⋯
I/flutter (13124):   parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
I/flutter (13124):   constraints: BoxConstraints(w=0.0, h=0.0)
I/flutter (13124):   size: Size(0.0, 0.0)
I/flutter (13124):   transform matrix:
I/flutter (13124):     [0] -Infinity,NaN,NaN,0.0
I/flutter (13124):     [1] NaN,-Infinity,NaN,-80.0
I/flutter (13124):     [2] NaN,NaN,-Infinity,0.0
I/flutter (13124):     [3] NaN,NaN,NaN,1.0
I/flutter (13124):   origin: null
I/flutter (13124):   alignment: bottomCenter
I/flutter (13124):   textDirection: ltr
I/flutter (13124):   transformHitTests: true
I/flutter (13124): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (13124):     child: RenderDecoratedBox#09ad1 NEEDS-PAINT
I/flutter (13124):       child: RenderPadding#cdd55 NEEDS-PAINT
I/flutter (13124):         child: RenderPositionedBox#e7a35 NEEDS-PAINT
I/flutter (13124):           child: RenderConstrainedBox#1a984 NEEDS-PAINT
I/flutter (13124):             child: RenderStack#7e1d5 NEEDS-PAINT
I/flutter (13124): ════════════════════════════════════════════════════════════════════════════════════════════════════
Reloaded 60 of 1972 libraries in 1,802ms.
```

```
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-GB)
iOS Simulator - iOS 14.3
```

**Comment by flschweiger** [comment]
Looks like there's an issue with the matrix transform trying to get some metrics from the Flutter window. Maybe it's because of the migration to `FlutterView` which is causing this?

**Comment by passsy** [comment]
Haven't seen this in a long time, was most likely a Flutter error that got fixed by now
