### ISSUE TITLE
Wiredash Exception during app start

### ISSUE THREAD

**Issue by Purus** [wiredashio/wiredash-sdk#142]
Kindly let me know if you need any other information.

```
I/flutter (12490): ══╡ EXCEPTION CAUGHT BY RENDERING LIBRARY ╞═════════════════════════════════════════════════════════
I/flutter (12490): The following assertion was thrown during paint():
I/flutter (12490): 'package:flutter/src/rendering/layer.dart': Failed assertion: line 1551 pos 12:
I/flutter (12490): 'value!.storage.every((double component) => component.isFinite)': is not true.
I/flutter (12490): 
I/flutter (12490): Either the assertion indicates an error in the framework itself, or we should provide substantially
I/flutter (12490): more information in this error message to help you determine and fix the underlying cause.
I/flutter (12490): In either case, please report this assertion by filing a bug on GitHub:
I/flutter (12490):   https://github.com/flutter/flutter/issues/new?template=2_bug.md
I/flutter (12490): 
I/flutter (12490): The relevant error-causing widget was:
I/flutter (12490):   Transform
I/flutter (12490):   file:///H:/flutter/.pub-cache/hosted/pub.dartlang.org/wiredash-0.6.2/lib/src/capture/capture.dart:184:22
I/flutter (12490): 
I/flutter (12490): When the exception was thrown, this was the stack:
I/flutter (12490): #2      TransformLayer.transform= (package:flutter/src/rendering/layer.dart:1551:12)
I/flutter (12490): #3      PaintingContext.pushTransform (package:flutter/src/rendering/object.dart:576:13)
I/flutter (12490): #4      RenderTransform.paint (package:flutter/src/rendering/proxy_box.dart:2361:25)
I/flutter (12490): #5      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2322:7)
I/flutter (12490): #6      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
I/flutter (12490): #7      RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2805:15)
I/flutter (12490): #8      RenderStack.paintStack (package:flutter/src/rendering/stack.dart:629:5)
I/flutter (12490): #9      RenderStack.paint (package:flutter/src/rendering/stack.dart:639:7)
I/flutter (12490): #10     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2322:7)
I/flutter (12490): #11     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
I/flutter (12490): #12     _RenderColoredBox.paint (package:flutter/src/widgets/basic.dart:7694:15)
I/flutter (12490): #13     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2322:7)
I/flutter (12490): #14     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
I/flutter (12490): #15     RenderView.paint (package:flutter/src/rendering/view.dart:200:15)
I/flutter (12490): #16     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2322:7)
I/flutter (12490): #17     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:140:11)
I/flutter (12490): #18     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
I/flutter (12490): #19     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:978:29)
I/flutter (12490): #20     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:455:19)
I/flutter (12490): #21     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:874:13)
I/flutter (12490): #22     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
I/flutter (12490): #23     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
I/flutter (12490): #24     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
I/flutter (12490): #25     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:865:7)
I/flutter (12490): (elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
I/flutter (12490): 
I/flutter (12490): The following RenderObject was being processed when the exception was fired: RenderTransform#807d3:
I/flutter (12490):   needs compositing
I/flutter (12490):   creator: Transform ← AnimatedBuilder ← Stack ← CaptureProvider ←
I/flutter (12490):     Capture-[LabeledGlobalKey<CaptureState>#e460a] ← ColoredBox ← Container ← Directionality ←
I/flutter (12490):     MediaQuery ← WiredashScaffold ← _InheritedWiredashTheme ← WiredashTheme ← ⋯
I/flutter (12490):   parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
I/flutter (12490):   constraints: BoxConstraints(w=0.0, h=0.0)
I/flutter (12490):   size: Size(0.0, 0.0)
I/flutter (12490):   transform matrix:
I/flutter (12490):     [0] -Infinity,NaN,NaN,0.0
I/flutter (12490):     [1] NaN,-Infinity,NaN,-80.0
I/flutter (12490):     [2] NaN,NaN,-Infinity,0.0
I/flutter (12490):     [3] NaN,NaN,NaN,1.0
I/flutter (12490):   origin: null
I/flutter (12490):   alignment: Alignment.bottomCenter
I/flutter (12490):   textDirection: ltr
I/flutter (12490):   transformHitTests: true
I/flutter (12490): This RenderObject had the following descendants (showing up to depth 5):
I/flutter (12490):     child: RenderDecoratedBox#f0778 NEEDS-PAINT
I/flutter (12490):       child: RenderPadding#c7004 NEEDS-PAINT
I/flutter (12490):         child: RenderPositionedBox#034c2 NEEDS-PAINT
I/flutter (12490):           child: RenderConstrainedBox#aa082 NEEDS-PAINT
I/flutter (12490):             child: RenderStack#6e059 NEEDS-PAINT
I/flutter (12490): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (12490): ----------------FIREBASE CRASHLYTICS----------------
I/flutter (12490): The following exception was thrown during paint():
I/flutter (12490): 'package:flutter/src/rendering/layer.dart': Failed assertion: line 1551 pos 12: 'value!.storage.every((double component) => component.isFinite)': is not true.
I/flutter (12490): 
I/flutter (12490): debugCreator: Transform ← AnimatedBuilder ← Stack ← CaptureProvider ← Capture-[LabeledGlobalKey<CaptureState>#e460a] ← ColoredBox ← Container ← Directionality ← MediaQuery ← WiredashScaffold ← _InheritedWiredashTheme ← WiredashTheme ← ⋯
I/flutter (12490): The following RenderObject was being processed when the exception was fired: RenderTransform#807d3
I/flutter (12490): RenderObject: RenderTransform#807d3
I/flutter (12490): 
I/flutter (12490): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:46:39)
I/flutter (12490): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
I/flutter (12490): #2      TransformLayer.transform= (package:flutter/src/rendering/layer.dart:1551:12)
I/flutter (12490): #3      PaintingContext.pushTransform (package:flutter/src/rendering/object.dart:576:13)
I/flutter (12490): #4      RenderTransform.paint (package:flutter/src/rendering/proxy_box.dart:2361:25)
I/flutter (12490): #5      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2322:7)
I/flutter (12490): #6      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
I/flutter (12490): #7      RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2805:15)
I/flutter (12490): #8      RenderStack.paintStack (package:flutter/src/rendering/stack.dart:629:5)
I/flutter (12490): #9      RenderStack.paint (package:flutter/src/rendering/stack.dart:639:7)
I/flutter (12490): #10     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2322:7)
I/flutter (12490): #11     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
I/flutter (12490): #
I/flutter (12490): ----------------------------------------------------
```

**Comment by passsy** [comment]
Thanks for reporting. This error already popped up in the past https://github.com/wiredashio/wiredash-sdk/issues/118 but we have too little information to reproduce it.

Which flutter version are you using?
What platform is your app running on?
Are you showing a PlatformView?

**Comment by Purus** [comment]
I have the very latest Flutter version released few days back.

I am testing only in android. Using Red Mi Note 7 pro real device.

I am not using platform view. I use office Google ads package.. Not sure if
this is related..

**Comment by passsy** [comment]
Yes, the ads package uses platform views under the hood. Thanks for the detail. I hope we can figure it out

**Comment by Purus** [comment]
Any luck with this? Please let me know if you need any information to proceed. I am getting this more often now in Crash Analytics dashboards.

**Comment by passsy** [comment]
Related to #118, must be revisited

**Comment by passsy** [comment]
Haven't seen this in a long time, was most likely a Flutter error that got fixed by now
