### ISSUE TITLE
Exception when changing gesture mode on Android

### ISSUE THREAD

**Issue by TheJulianJES** [wiredashio/wiredash-sdk#154]
Wiredash version: 0.7.0+1
Flutter version: 2.5.1

Opening an app with Wiredash, then going home (not quitting the app -- just putting it in the background), changing the gesture modes (tried on Android 11 Emulator) from 3 buttons to gesture navigations, causes the following exception:

```
======== Exception caught by rendering library =====================================================
The following assertion was thrown during paint():
'package:flutter/src/rendering/layer.dart': Failed assertion: line 1667 pos 12: 'value!.storage.every((double component) => component.isFinite)': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

The relevant error-causing widget was: 
  Transform Transform:file:///Users/User/flutter/.pub-cache/hosted/pub.dartlang.org/wiredash-0.7.0+1/lib/src/capture/capture.dart:184:22
When the exception was thrown, this was the stack: 
#2      TransformLayer.transform= (package:flutter/src/rendering/layer.dart:1667:12)
#3      PaintingContext.pushTransform (package:flutter/src/rendering/object.dart:578:13)
#4      RenderTransform.paint (package:flutter/src/rendering/proxy_box.dart:2398:27)
#5      RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#6      PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#7      RenderBoxContainerDefaultsMixin.defaultPaint (package:flutter/src/rendering/box.dart:2794:15)
#8      RenderStack.paintStack (package:flutter/src/rendering/stack.dart:629:5)
#9      RenderStack.paint (package:flutter/src/rendering/stack.dart:645:7)
#10     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#11     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#12     _RenderColoredBox.paint (package:flutter/src/widgets/basic.dart:8143:15)
#13     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#14     PaintingContext.paintChild (package:flutter/src/rendering/object.dart:189:13)
#15     RenderView.paint (package:flutter/src/rendering/view.dart:209:15)
#16     RenderObject._paintWithContext (package:flutter/src/rendering/object.dart:2409:7)
#17     PaintingContext._repaintCompositedChild (package:flutter/src/rendering/object.dart:141:11)
#18     PaintingContext.repaintCompositedChild (package:flutter/src/rendering/object.dart:100:5)
#19     PipelineOwner.flushPaint (package:flutter/src/rendering/object.dart:979:29)
#20     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:455:19)
#21     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
#22     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:319:5)
#23     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1143:15)
#24     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1080:9)
#25     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:863:7)
(elided 13 frames from class _AssertionError, class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
The following RenderObject was being processed when the exception was fired: RenderTransform#1ceaa
...  needs compositing
...  parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
...  constraints: BoxConstraints(w=0.0, h=0.0)
...  size: Size(0.0, 0.0)
...  transform matrix: [0] -Infinity,NaN,NaN,0.0
[1] NaN,-Infinity,NaN,-80.0
[2] NaN,NaN,-Infinity,0.0
[3] NaN,NaN,NaN,1.0
...  origin: null
...  alignment: Alignment.bottomCenter
...  textDirection: ltr
...  transformHitTests: true
RenderObject: RenderTransform#1ceaa
  needs compositing
  parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
  constraints: BoxConstraints(w=0.0, h=0.0)
  size: Size(0.0, 0.0)
  transform matrix: [0] -Infinity,NaN,NaN,0.0
[1] NaN,-Infinity,NaN,-80.0
[2] NaN,NaN,-Infinity,0.0
[3] NaN,NaN,NaN,1.0
  origin: null
  alignment: Alignment.bottomCenter
  textDirection: ltr
  transformHitTests: true
...  child: RenderDecoratedBox#a35ce NEEDS-PAINT
...    needs compositing
...    parentData: <none> (can use size)
...    constraints: BoxConstraints(w=0.0, h=0.0)
...    size: Size(0.0, 0.0)
...    decoration: BoxDecoration
...      color: Color(0xfff5f6f8)
...      border: Border.all(BorderSide(Color(0xffccd2d9), 2.0, BorderStyle.solid))
...      borderRadius: BorderRadius.circular(16.0)
...    configuration: ImageConfiguration(bundle: PlatformAssetBundle#a876b(), devicePixelRatio: 1.0, textDirection: TextDirection.ltr, platform: android)
...    child: RenderPadding#1352e NEEDS-PAINT
...      needs compositing
...      parentData: <none> (can use size)
...      constraints: BoxConstraints(w=0.0, h=0.0)
...      size: Size(0.0, 0.0)
...      padding: EdgeInsets.all(2.0)
...      textDirection: ltr
...      child: RenderPositionedBox#cd1a4 NEEDS-PAINT
...        needs compositing
...        parentData: offset=Offset(2.0, 2.0) (can use size)
...        constraints: BoxConstraints(w=0.0, h=0.0)
...        size: Size(0.0, 0.0)
...        alignment: AlignmentDirectional.centerEnd
...        textDirection: ltr
...        widthFactor: expand
...        heightFactor: expand
...        child: RenderConstrainedBox#2f954 NEEDS-PAINT
...          needs compositing
...          parentData: offset=Offset(0.0, 0.0) (can use size)
...          constraints: BoxConstraints(w=0.0, h=0.0)
...          size: Size(0.0, 0.0)
...          additionalConstraints: BoxConstraints(w=80.0, 0.0<=h<=Infinity)
====================================================================================================
```

**Comment by passsy** [comment]
Thanks for the report. This crash was reported a few times now, but we've never found a way to reproduce it.

Will test it and keep you updated
