### ISSUE TITLE
Unable to load asset: packages/wiredash/assets/images/logo_grey.png

### ISSUE THREAD

**Issue by eggnstone** [wiredashio/wiredash-sdk#189]
Using `wiredash: ^0.7.0+1`

```
I/flutter ( 7244): ══╡ EXCEPTION CAUGHT BY IMAGE RESOURCE SERVICE ╞════════════════════════════════════════════════════
I/flutter ( 7244): The following assertion was thrown resolving an image codec:
I/flutter ( 7244): Unable to load asset: packages/wiredash/assets/images/logo_grey.png
I/flutter ( 7244): 
I/flutter ( 7244): When the exception was thrown, this was the stack:
I/flutter ( 7244): #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:237:7)
I/flutter ( 7244): <asynchronous suspension>
I/flutter ( 7244): #1      AssetBundleImageProvider._loadAsync (package:flutter/src/painting/image_provider.dart:675:14)
I/flutter ( 7244): <asynchronous suspension>
I/flutter ( 7244): 
I/flutter ( 7244): Image provider: AssetImage(bundle: null, name: "packages/wiredash/assets/images/logo_grey.png")
I/flutter ( 7244): Image key: AssetBundleImageKey(bundle: PlatformAssetBundle#13b11(), name:
[Error] 12:52:13 ##################################################
I/flutter ( 7244):   "packages/wiredash/assets/images/logo_grey.png", scale: 1.0)
I/flutter ( 7244): ════════════════════════════════════════════════════════════════════════════════════════════════════
[Error] 12:52:13 # GoogleCrashlyticsService/FlutterError.onError 
I/flutter ( 7244): Another exception was thrown: Unable to load asset: packages/wiredash/assets/images/pen.png
D/EGL_emulation( 7244): app_time_stats: avg=63534.07ms min=111.42ms max=189561.80ms count=3
[Error] 12:52:13 #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:237:7)
<asynchronous suspension>
#1      AssetBundleImageProvider._loadAsync (package:flutter/src/painting/image_provider.dart:675:14)
<asynchronous suspension>
```

**Comment by eggnstone** [comment]
Hm, can't reproduce now anymore.
I guess you can close the issue.
