### ISSUE TITLE
Wiredash couldn't access your app's root navigator.

### ISSUE THREAD

**Issue by zyllus17** [wiredashio/wiredash-sdk#203]
<details>
<summary>Error in console</summary>
<br>

```log
════════ Exception caught by gesture ═══════════════════════════════════════════
The following assertion was thrown while handling a gesture:
Wiredash couldn't access your app's root navigator.

This is likely to happen when you forget to add the navigator key to your 
Material- / Cupertino- or WidgetsApp widget. 

To fix this, simply assign the same GlobalKey you assigned to Wiredash 
to your Material- / Cupertino- or WidgetsApp widget, like so:

return Wiredash(
  projectId: "YOUR-PROJECT-ID",
  secret: "YOUR-SECRET",
  navigatorKey: _navigatorKey, // <-- should be the same
  child: MaterialApp(
    navigatorKey: _navigatorKey, // <-- should be the same
    title: 'Flutter Demo',
    home: ...
  ),
);

For more info on how to setup Wiredash, check out 
https://github.com/wiredashio/wiredash-sdk

If this did not fix the issue, please file an issue at 
https://github.com/wiredashio/wiredash-sdk/issues

Thanks!
'package:wiredash/src/feedback/feedback_model.dart':
package:wiredash/…/feedback/feedback_model.dart:1
Failed assertion: line 112 pos 12: '_navigatorKey.currentState != null'


When the exception was thrown, this was the stack
#2      FeedbackModel.show
package:wiredash/…/feedback/feedback_model.dart:112
#3      WiredashState.show
package:wiredash/src/wiredash_widget.dart:228
#4      WiredashController.show
package:wiredash/src/wiredash_controller.dart:49
#5      AppDrawer.build.<anonymous closure>
package:flutter_hub/widgets/app_drawer.dart:54
#6      _InkResponseState._handleTap
package:flutter/…/material/ink_well.dart:989
#7      GestureRecognizer.invokeCallback
package:flutter/…/gestures/recognizer.dart:198
#8      TapGestureRecognizer.handleTapUp
package:flutter/…/gestures/tap.dart:608
#9      BaseTapGestureRecognizer._checkUp
package:flutter/…/gestures/tap.dart:296
#10     BaseTapGestureRecognizer.acceptGesture
package:flutter/…/gestures/tap.dart:267
#11     GestureArenaManager.sweep
package:flutter/…/gestures/arena.dart:157
#12     GestureBinding.handleEvent
package:flutter/…/gestures/binding.dart:443
#13     GestureBinding.dispatchEvent
package:flutter/…/gestures/binding.dart:419
#14     RendererBinding.dispatchEvent
package:flutter/…/rendering/binding.dart:322
#15     GestureBinding._handlePointerEventImmediately
package:flutter/…/gestures/binding.dart:374
#16     GestureBinding.handlePointerEvent
package:flutter/…/gestures/binding.dart:338
#17     GestureBinding._flushPointerEventQueue
package:flutter/…/gestures/binding.dart:296
#18     GestureBinding._handlePointerDataPacket
package:flutter/…/gestures/binding.dart:279
#22     _invoke1 (dart:ui/hooks.dart:170:10)
#23     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:331:7)
#24     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
(elided 5 frames from class _AssertionError and dart:async)
Handler: "onTap"
Recognizer: TapGestureRecognizer#60408
    debugOwner: GestureDetector
    state: ready
    won arena
    finalPosition: Offset(114.7, 350.1)
    finalLocalPosition: Offset(94.7, 22.4)
    button: 1
    sent tap down
════════════════════════════════════════════════════════════════════════════════
```
</details>

I tried fixing the error according to the hint in the console but it isn't working.

My code-

```dart
class MyApp extends StatelessWidget {
  final _navigatorKey = GlobalKey<NavigatorState>();
  @override
  Widget build(BuildContext context) {
    return Wiredash(
      projectId: WireDashAPI.projectID,
      secret: WireDashAPI.secret,
      navigatorKey: _navigatorKey,
      child: ScreenUtilInit(
        designSize: Size(411, 823),
        builder: () => MaterialApp(
          navigatorKey: _navigatorKey,
          debugShowCheckedModeBanner: false,
          builder: DevicePreview.appBuilder,
          title: 'App',
          theme: AppTheme.appTheme,
          home: HomeScreen(),
        ),
      ),
    );
  }
}
```
It was working perfectly before but I am getting this error now everytime.

**Comment by passsy** [comment]
Thanks for the report.

What's your Flutter version?

Hint: We expected problems like that to occur. That's why we removed the need for `navigatorKey` in Wiredash 1.0.0 alpha version. Give it a try ✌️

**Comment by zyllus17** [comment]
I tried the alpha release and it throws a new error but it works this time.

<details>
<summary>Error in console</summary>
<br>

```log
Reload already in progress, ignoring request: Warning: Operand of null-aware operation '!' has type 'WiredashController' which excludes null.
lib/widgets/app_drawer.dart:54
- 'WiredashController' is from 'package:wiredash/src/wiredash_controller.dart' ('/D:/flutter/.pub-cache/hosted/pub.dartlang.org/wiredash-1.0.0-alpha.6/lib/src/wiredash_controller.dart').
package:wiredash/src/wiredash_controller.dart:1
                onTap: () => Wiredash.of(context)!.show(),
                                      ^
```
</details>

and I still have to use the `_navigatorKey` as it throws error if I am not using it.

Also the older design looked better than the new one.

**Comment by passsy** [comment]
It's because of the context you pass into `Wiredash.of(context)`. The method can't find `Wiredash` as parent Widget. Please double-check the context you're using has access to Wiredash. (You might want to wrap the caller in a `Builder`). Make sure that you put the `Wiredash` widget at the very top of the app.
