### ISSUE TITLE
MissingPluginException(No implementation found for method getAll on channel dev.fluttercommunity.plus/package_info)

### ISSUE THREAD

**Issue by alexgrusu** [wiredashio/wiredash-sdk#339]
**Describe the bug**
Going through the feedback process, the below exception is thrown.

**Stacktrace**
```
════════ Exception caught by wiredash ══════════════════════════════════════════
The following MissingPluginException was thrown:
MissingPluginException(No implementation found for method getAll on channel dev.fluttercommunity.plus/package_info)

When the exception was thrown, this was the stack:
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
platform_channel.dart:332
<asynchronous suspension>
#1      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:534:43)
platform_channel.dart:534
<asynchronous suspension>
#2      MethodChannelPackageInfo.getAll (package:package_info_plus_platform_interface/method_channel_package_info.dart:13:17)
method_channel_package_info.dart:13
<asynchronous suspension>
#3      PackageInfo.fromPlatform (package:package_info_plus/package_info_plus.dart:41:26)
package_info_plus.dart:41
<asynchronous suspension>
#4      MetaDataCollector._collectAppInfo (package:wiredash/src/metadata/meta_data_collector.dart:82:27)
meta_data_collector.dart:82
<asynchronous suspension>
#5      MetaDataCollector.collectFixedMetaData.<anonymous closure>.<anonymous closure> (package:wiredash/src/metadata/meta_data_collector.dart:49:37)
meta_data_collector.dart:49
<asynchronous suspension>
<asynchronous suspension>
<asynchronous suspension>
#8      MetaDataCollector.collectFixedMetaData (package:wiredash/src/metadata/meta_data_collector.dart:43:21)
meta_data_collector.dart:43
<asynchronous suspension>
#9      FeedbackModel.createFeedback (package:wiredash/src/feedback/feedback_model.dart:405:9)
feedback_model.dart:405
<asynchronous suspension>
#10     _FutureBuilderState._subscribe.<anonymous closure> (package:flutter/src/widgets/async.dart:624:31)
async.dart:624
<asynchronous suspension>
(elided 2 frames from dart:async)

Failed to collect package info
```

**Wiredash SDK Info**
2.1.0

**Flutter SDK**
```
[✓] Flutter (Channel stable, 3.19.0, on macOS 14.2.1 23C71 darwin-arm64 (Rosetta), locale en-RO)
    • Flutter version 3.19.0 on channel stable at /Users/epsilon/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision bae5e49bc2 (6 weeks ago), 2024-02-13 17:46:18 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1
```

**Screenshots**

**Comment by passsy** [comment]
Thanks for sharing. Wiredash works fine on Flutter 3.19 for many projects. There might be an incompatibility in your dependencies, that causes this error.

Which versions of package_info_plus are you using? (check pubspec.lock)
And on which platform are you running the code?

Please try `flutter pub upgrade`
